# When adding new entries keep the list in alphabetical order
CFLAGS_scm.o :=$(call as-instr,.arch_extension sec,-DREQUIRES_SEC=1)

obj-$(CONFIG_SEC_THERMISTOR) += sec_thermistor.o msm8916-thermistor.o
